
lang: ru-RU
encoding: utf-8
url: http://prog.msk.ru
permalink: pretty
highlighter: rouge
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/:num"

feed:
  path: feed.atom
