lang: ru-RU
encoding: utf-8
timezone: Europe/Moscow

url: https://prog.msk.ru
title: Московский клуб программистов
image: "/assets/images/post/default.png"

permalink: pretty
highlighter: rouge
markdown: kramdown
input: GFM
logo_location: "/assets/images/logo.svg"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
paginate_path: "results/:num/"

exclude: ['README.md']

sass:
  style: compressed
